variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "vpc_name" {}
variable "cidr" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "rds_port" {}
variable "rds_name" {}
variable "rds_username" {}
variable "rds_password" {}
