apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
  labels:
    project: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
     project: {{ .Release.Name }}
  template:
    metadata:
     labels:
       project: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.containers.image }}
          ports:
            - containerPort: 80