name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
  #   - name: download python
  #     run: | 
  #       python -m pip install --upgrade pip
  #       pip install flask yaml2 psycopg2
  #       sudo apt-get --yes install python3-psycopg2 curl
  #   - name: Run unittest
  #     run: |
  #       python test_show_result.py

  login:
    runs-on: ubuntu-latest
    needs: Unit_test
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          # username: ${{ secrets.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: errbx
          password: 1291d30f-9c5d-497f-ad16-10986bcbfda1


  # Deploy:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   - name: Build and push
  #     uses: docker/build-push-action@v2
  #     with:
  #       context: .
  #       push: true
  #       tags: errbx/epam_task04:latest
