name: Python application
env:
  IMAGE_TAG: ${{ github.sha }}

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  Unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: download python
      run: | 
        python -m pip install --upgrade pip
        pip install flask yaml2 psycopg2
        sudo apt-get --yes install python3-psycopg2 curl
    - name: Run unittest
      run: |
        python test_show_result.py

  Build:
    name: Build and push to Docker hub registry
    runs-on: ubuntu-latest
    needs: Unit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Github regestry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: errbx/epam_task:${{ env.IMAGE_TAG }}

  Deploy:
    name: Deploy from Docker hub registry
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update config k8s_epam
      run: |
        aws eks --region eu-west-3 update-kubeconfig --name k8s_epam

    - name: Upgrade release
      uses: hiberbee/github-action-helm@latest
      with:
        helm-command: upgrade epam-dev app-HelmChart/ --set container.image=errbx/epam_task:${{ env.IMAGE_TAG }}