# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask yaml2 psycopg2
        sudo apt-get --yes install python3-psycopg2 curl
  
  Unit_test:
    runs-on: ubuntu-latest
    - name: Run unittest
      run: |
        python test_show_result.py

    # - name: Build
    #   run: |
    #     docker build -f dockerfile -t errbx/epam_task03:latest .
    #     docker login -u errbx --password-stdin "Vfhnvfhn123" docker.com
    #     docker push errbx/epam_task03:latest

  Build:
    runs-on: ubuntu-latest
    needs: Unit_test
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          registry: registry.gitlab.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # username: errbx
        # password: 4d919cfd-3e75-4a57-9da5-a292dd69b666

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: errbx/epam_task04:latest
