name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare_step_1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
  
  prepare_step_2:
    runs-on: ubuntu-latest
    needs: prepare_step_1
    steps:
    - name:
      run: | 
        python -m pip install --upgrade pip
        pip install flask yaml2 psycopg2
        sudo apt-get --yes install python3-psycopg2 curl
  
  unit_test:
    needs: prepare_step_2
    runs-on: ubuntu-latest
    steps:
    - name: Run unittest
      run: |
        python test_show_result.py

  Build:
    name: Login to DockerHub
    needs: unit_test
    uses: docker/login-action@v1
    with:
        registry: registry.gitlab.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: errbx/epam_task04:latest
