name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: download python
      run: | 
        python -m pip install --upgrade pip
        pip install flask yaml2 psycopg2
        sudo apt-get --yes install python3-psycopg2 curl
    - name: Run unittest
      run: |
        python test_show_result.py

  Build:
    runs-on: ubuntu-latest
    needs: Unit_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/epum_task004:latest

  Deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Configure k8s_epam
      run: |
        aws eks --region eu-west-3 update-kubeconfig --name k8s_epam

    - name: Update deployment k8s_epam
      run: |
        kubectl apply -f k8s/deployment.yml
